const arrayFill = require('./arrayFill.js'); 
const concat = require('./concat.js');
const copyWithin = require('./copyWithin.js');
const entries = require('./entries.js');
const every = require('./every.js');
const filter = require('./filter.js');
const find = require('./find.js');
const findIndex = require('./findIndex.js');
const flat = require('./flat.js');
const flatMap = require('./flatMap.js');
const forEach = require('./forEach.js');
const from = require('./from.js');
const includes = require('./includes.js');
const indexOf = require('./indexOf.js');
const isArray = require('./isArray.js');
const Iterate = require('./Iterate.js'); 
const join = require('./join.js');
const unshift = require('./unshift');
const value = require('./value'); 
arrayFill();
Iterate();
concat();
copyWithin();
entries();
every();
value();
unshift();
filter();
find();
findIndex();
flat();
flatMap();
forEach();
from();
includes();
indexOf();
isArray();
join();